# Generated by Django 5.2.3 on 2025-06-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_user_id_users_id_user_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
