# Generated by Django 4.2.5 on 2026-04-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_last_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seen_books',
            field=models.JSONField(default=list),
        ),
    ]
