# Generated by Django 5.2.3 on 2026-03-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_user_message_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='its_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
