# Generated by Django 4.2.5 on 2026-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_seen_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='libro_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
