# Generated by Django 5.2.3 on 2026-04-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_username_message_its_from_user'),
        ('chat', '0005_message_libro_ids'),
    ]

    operations = [
    ]
