# Generated by Django 5.2.3 on 2025-09-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['send_at']},
        ),
    ]
